<a href="https://colab.research.google.com/github/eboekenh/Pandas/blob/main/Ex_1_test_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [ ]:
help(np.random)

In [16]:
s=pd.Series(np.random.randint(70,101,10))
s

0     98
1     99
2     91
3     98
4     93
5     83
6     87
7    100
8     88
9     73
dtype: int64

In [17]:
months = ["September", "October", "November", "December", "January", "February", "March", "April", "May", "June"]
print(months)

['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April', 'May', 'June']

In [19]:
notes = pd.Series(data=s.values, index=months)
notes

September     98
October       99
November      91
December      98
January       93
February      83
March         87
April        100
May           88
June          73
dtype: int64

In [20]:
s.mean()

np.float64(91.0)

In [25]:
s[:6].mean()

np.float64(93.66666666666667)

In [27]:
s[-6:].mean()

np.float64(87.33333333333333)